### ISSUE TITLE
Validate shortcode service configurations (Case 173693)

### ISSUE THREAD

**Issue by MalteWunsch** [webfactory/WebfactoryShortcodeBundle#35]
I've screwed up a shortcode configuration by passing a positional parameter to the `EmbeddedShortcodeHandler` like this:

```
    webfactory.shortcode.x:
        parent: 'webfactory.shortcode.embed_inline_for_shortcode_handler'
        class: 'Webfactory\ShortcodeBundle\Handler\EmbeddedShortcodeHandler'
        arguments:
            - 'My\ShortcodeController::myAction'
        tags: [...]
```

which should have been a named parameter:
```
        arguments:
            $controllerName: 'My\ShortcodeController::myAction'
```

I wish we would throw an exception in this case (and similar cases).
